#include "InspectionReport.h"
#include <iostream>
using namespace std;

InspectionReport::InspectionReport(
    string id, string date,
    string by, FileHandler& inf) : Report(id, date, by), inspFile(inf) {
}

void InspectionReport::generate() {
    results.clear();
    vector<string> lines = inspFile.readAllLines();

    for (int i = 0; i < (int)lines.size(); i++) {
        Inspection ins;
        ins.fromString(lines[i]);
        results.push_back(ins);
    }
}

void InspectionReport::display() {
    cout << "\n========================================" << endl;
    cout << "  INSPECTION REPORT" << endl;
    cout << "  Generated By : " << generatedBy << endl;
    cout << "  Generated On : " << generatedDate << endl;
    cout << "========================================" << endl;

    if (results.empty()) {
        cout << "No inspections found." << endl;
    }
    else {
        for (int i = 0; i < (int)results.size(); i++) {
            results[i].displayInfo();
        }
        cout << "Total Inspections: " << results.size() << endl;
    }
    cout << "========================================\n" << endl;
}
