#include "NewCustomersReport.h"
#include<iostream>
using namespace std;

NewCustomersReport::NewCustomersReport(
    string id, string date, string by,
    string m, string y, FileHandler& cf)
    : Report(id, date, by),
    month(m), year(y), customerFile(cf) {
}

// ─────────────────────────────────────────────────────────────
// generate — filter customers registered in given month/year
// Registration date format: DD-MM-YYYY
// ─────────────────────────────────────────────────────────────
void NewCustomersReport::generate() {
    results.clear();
    vector<string> lines = customerFile.readAllLines();

    for (int i = 0; i < (int)lines.size(); i++) {
        Customer c;
        c.fromString(lines[i]);

        string regDate = c.getRegistrationDate(); // DD-MM-YYYY
        if (regDate.size() >= 10) {
            string recMonth = regDate.substr(3, 2);  // MM
            string recYear = regDate.substr(6, 4);  // YYYY
            if (recMonth == month && recYear == year) {
                results.push_back(c);
            }
        }
    }
}

// display — print report to screen
// ─────────────────────────────────────────────────────────────
void NewCustomersReport::display() {
    cout << "\n========================================" << endl;
    cout << "  NEW CUSTOMERS REPORT" << endl;
    cout << "  Month: " << month << "  Year: " << year << endl;
    cout << "  Generated By  : " << generatedBy << endl;
    cout << "  Generated On  : " << generatedDate << endl;
    cout << "========================================" << endl;

    if (results.empty()) {
        cout << "No new customers found for "
            << month << "/" << year << endl;
    }
    else {
        for (int i = 0; i < (int)results.size(); i++) {
            results[i].displayInfo();
        }
        cout << "Total New Customers: "
            << results.size() << endl;
    }
    cout << "========================================\n" << endl;
}