#include "PendingClaimsReport.h"
#include <iostream>
using namespace std;

PendingClaimsReport::PendingClaimsReport(
    string id, string date,
    string by, FileHandler& cf) : Report(id, date, by), claimFile(cf) {
}

void PendingClaimsReport::generate() {
    results.clear();
    vector<string> lines = claimFile.readAllLines();

    for (int i = 0; i < (int)lines.size(); i++) {
        Claim c;
        c.fromString(lines[i]);
        if (c.getStatus() == "Pending") {
            results.push_back(c);
        }
    }
}

void PendingClaimsReport::display() {
    cout << "\n========================================" << endl;
    cout << "  PENDING CLAIMS REPORT" << endl;
    cout << "  Generated By : " << generatedBy << endl;
    cout << "  Generated On : " << generatedDate << endl;
    cout << "========================================" << endl;

    if (results.empty()) {
        cout << "No pending claims found." << endl;
    }
    else {
        for (int i = 0; i < (int)results.size(); i++) {
            results[i].displayInfo();
        }
        cout << "Total Pending: " << results.size() << endl;
    }
    cout << "========================================\n" << endl;
}